export const afterSellerDesData = [
  "Be available.",
  "Think long term. ",
  "Know Your Strengths.",
  "Know and believe in your product.",
  "Invest your time wisely.",
  "Build Relationships.",
  "Maintain connections with past clients.",
  "Don’t only focus on selling.",
  "Conduct a comparative market analysis.",
  "Be transparent with your buyer.",
  "Avoid making assumptions.",
  "Ability to listen.",
  "Become a consultant rather than a sales officer.",
];