export const afterSellerDesData = [
  "Be available.",
  "Think long term. ",
  "Know Your Strengths.",
  "Know and believe in your product.",
  "Invest your time wisely.",
  "Build Relationships.",
  "Maintain connections with past clients.",
  "Don’t only focus on selling.",
  "Conduct a comparative market analysis.",
  "Be transparent with your buyer.",
  "Avoid making assumptions.",
  "Ability to listen.",
  "Become a consultant rather than a sales officer.",
];

export const sellerDetailList = [
  {
    name: "Mr. Shiplo Rana",
    profession: "Private Service",
    location: "Bashundhara R/A, Dhaka",
    size: "1100 – 1300 sqft",
    schedule: "Friday and Saturday",
  },
  {
    name: "Md. Abu Sufian",
    profession: "Lawyer",
    location: "Mohammadpur, Dhaka",
    size: "1200 – 1400 sqft",
    schedule: "Friday and Saturday",
  },
  {
    name: "Mr. Md. Abduj Jaher",
    profession: "Private Service",
    location: "Aftabnagar, Dhaka",
    size: "1500 – 1600 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mr. Asadur Rahman",
    profession: "Banker",
    location: "Aftabnagar, Dhaka",
    size: "1400 – 1600 sqft",
    schedule: "Friday and Saturday",
  },
  {
    name: "Mr. S M Shafiul Muznabin",
    profession: "Accountant",
    location: "Agargaon, Dhaka",
    size: "1000 – 1100 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mrs. Lata Zafa",
    profession: "Teacher",
    location: "Badda, Dhaka",
    size: "1200 – 1300 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mr. Mamunur Rashid ",
    profession: "Business",
    location: "Shantinagar, Dhaka",
    size: "1250 – 1350 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mrs. Nahida Sultana",
    profession: "-----",
    location: "Uttara, Dhaka",
    size: "1800 – 2000 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mrs. Nazma Akhter Lyzu",
    profession: "Doctor",
    location: "Uttara, Dhaka",
    size: "2000 – 2200 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mr. Md. Kamrul Hasan",
    profession: "Banker",
    location: "South Banasree, Dhaka",
    size: "1000 – 1100 sqft",
    schedule: "Friday or Saturday",
  },
  {
    name: "Mr. Rakibul Azam Chowdhury",
    profession: "Private Service",
    location: "Banasree, Dhaka",
    size: "1200 – 1300 sqft",
    schedule: "Friday",
  },
  {
    name: "Ms. Mahima Hoque",
    profession: "-----",
    location: "Surrround Dhanmondi, Dhaka",
    size: "2200 – 3000 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mr. Md. Tanvir Islam",
    profession: "-----",
    location: "Narinda or Gendaria, Dhaka",
    size: "1100 – 1500 sqft",
    schedule: "Not fix yet",
  },
  {
    name: "Mr. Ibrahim Adham",
    profession: "Private Service",
    location: "Green Road, Dhaka",
    size: "1000 – 1200 sqft",
    schedule: "Friday or Saturday",
  },
  {
    name: "Mr. Aktaruzzaman Tito",
    profession: "Business",
    location: "Mohammadpur, Dhaka",
    size: "1400 – 1600 sqft",
    schedule: "Not fix yet",
  },
];
